export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  ROLES: '/roles',
  SETTINGS: '/settings',
  // Employees
  EMPLOYEES: '/employees',
  EMPLOYEE_DETAIL: '/employees/:employeeCode',
  EMPLOYEE_CREATE: '/employees/new',
  // Leave
  LEAVE_APPLICATIONS: '/leave/applications',
  LEAVE_BALANCE: '/leave/balance',
  LEAVE_TYPES: '/leave/types',
  // Attendance
  ATTENDANCE: '/attendance',
  ATTENDANCE_LOGS: '/attendance/logs',
  ATTENDANCE_EXCEPTIONS: '/attendance/exceptions',
  // Phase 3
  NOTIFICATIONS: '/notifications',
  APPROVAL_QUEUE: '/approvals',
  WORKFLOWS: '/settings/workflows',
  RULE_SETS: '/settings/rules',
  FORMS: '/settings/forms',
  FORM_VIEW: '/forms/:formPublicId',
  // Organisation settings
  COMPANIES: '/settings/companies',
  DEPARTMENTS: '/settings/departments',
  DESIGNATIONS: '/settings/designations',
  LOCATIONS: '/settings/locations',
  AUTHORITY_SIGNATURES: '/settings/authority-signatures',
  // Admin
  USERS_MGMT: '/admin/users',
  // Payroll
  PAYROLL_DASHBOARD:  '/payroll',
  PAYROLL_COMPONENTS: '/payroll/components',
  PAYROLL_STRUCTURES: '/payroll/structures',
  PAYROLL_CYCLES:     '/payroll/cycles',
  PAYROLL_RUNS:       '/payroll/runs',
  PAYROLL_RUN_DETAIL: '/payroll/runs/:publicId',
  PAYROLL_INPUTS:     '/payroll/runs/:publicId/inputs',
  PAYROLL_PAYSLIPS:   '/payroll/payslips',
  PAYROLL_STATUTORY:  '/payroll/statutory-settings',
  PAYROLL_REPORTS:    '/payroll/reports',
  EMPLOYEE_SALARY:    '/employees/:employeeCode/salary',
  // Phase 5
  SHIFTS:             '/attendance/shifts',
  OVERTIME:           '/attendance/overtime',
  EXPENSE_CLAIMS:     '/expense/claims',
  PAYROLL_LOANS:      '/payroll/loans',
  PAYROLL_FNF:        '/payroll/fnf',
  // Phase 6
  REPORTS:            '/reports',
  ANALYTICS:          '/reports/analytics',
  INTEGRATIONS:       '/integrations',
  WEBHOOKS:           '/integrations/webhooks',
  PAYROLL_ACCOUNTING: '/payroll/accounting',
  NOT_FOUND: '*',
} as const;
