export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Authorization
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Tenant
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_ARCHIVED: 'TENANT_ARCHIVED',
  SLUG_TAKEN: 'SLUG_TAKEN',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Organization
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',

  // Employee
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_CODE_EXISTS: 'EMPLOYEE_CODE_EXISTS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',

  // Leave
  LEAVE_NOT_FOUND: 'LEAVE_NOT_FOUND',
  LEAVE_TYPE_NOT_FOUND: 'LEAVE_TYPE_NOT_FOUND',
  LEAVE_INSUFFICIENT_BALANCE: 'LEAVE_INSUFFICIENT_BALANCE',
  LEAVE_OVERLAPPING: 'LEAVE_OVERLAPPING',
  LEAVE_INVALID_TRANSITION: 'LEAVE_INVALID_TRANSITION',
  HOLIDAY_NOT_FOUND: 'HOLIDAY_NOT_FOUND',

  // Attendance
  ATTENDANCE_NOT_FOUND: 'ATTENDANCE_NOT_FOUND',
  ATTENDANCE_ALREADY_LOCKED: 'ATTENDANCE_ALREADY_LOCKED',
  ATTENDANCE_PUNCH_DUPLICATE: 'ATTENDANCE_PUNCH_DUPLICATE',
  SHIFT_NOT_FOUND: 'SHIFT_NOT_FOUND',

  // RBAC
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  CANNOT_DELETE_SYSTEM_ROLE: 'CANNOT_DELETE_SYSTEM_ROLE',

  // Plan / limits
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
  MODULE_NOT_ENABLED: 'MODULE_NOT_ENABLED',

  // Payroll
  PAYROLL_LOCKED: 'PAYROLL_LOCKED',

  // Workflow
  MAKER_CHECKER_REQUIRED: 'MAKER_CHECKER_REQUIRED',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_INSTANCE_NOT_FOUND: 'WORKFLOW_INSTANCE_NOT_FOUND',
  WORKFLOW_INSTANCE_EXISTS: 'WORKFLOW_INSTANCE_EXISTS',
  WORKFLOW_STEP_UNAUTHORIZED: 'WORKFLOW_STEP_UNAUTHORIZED',

  // Rule engine
  RULE_SET_NOT_FOUND: 'RULE_SET_NOT_FOUND',
  RULE_NOT_FOUND: 'RULE_NOT_FOUND',
  RULE_CONFLICT: 'RULE_CONFLICT',

  // Dynamic forms
  FORM_NOT_FOUND: 'FORM_NOT_FOUND',
  FORM_SUBMISSION_INVALID: 'FORM_SUBMISSION_INVALID',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // Request
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  NOT_FOUND: 'NOT_FOUND',

  // Async jobs
  JOB_QUEUED: 'JOB_QUEUED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
