export const PAYROLL_PERMISSIONS = {
  COMPONENT_VIEW:          'payroll.component.view',
  COMPONENT_MANAGE:        'payroll.component.manage',
  STRUCTURE_VIEW:          'payroll.structure.view',
  STRUCTURE_MANAGE:        'payroll.structure.manage',
  EMPLOYEE_SALARY_VIEW:    'payroll.employee_salary.view',
  EMPLOYEE_SALARY_ASSIGN:  'payroll.employee_salary.assign',
  EMPLOYEE_SALARY_REVISE:  'payroll.employee_salary.revise',
  CYCLE_MANAGE:            'payroll.cycle.manage',
  INPUTS_MANAGE:           'payroll.inputs.manage',
  RUN_VIEW:                'payroll.run.view',
  RUN_CREATE:              'payroll.run.create',
  RUN_FINALIZE:            'payroll.run.finalize',
  RUN_APPROVE:             'payroll.run.approve',
  RUN_ROLLBACK:            'payroll.run.rollback',
  PAYSLIP_VIEW:            'payroll.payslip.view',
  PAYSLIP_PUBLISH:         'payroll.payslip.publish',
  STATUTORY_MANAGE:        'payroll.statutory.manage',
  LOAN_VIEW:               'payroll.loan.view',
  LOAN_CREATE:             'payroll.loan.create',
  LOAN_APPROVE:            'payroll.loan.approve',
  FNF_VIEW:                'payroll.fnf.view',
  FNF_INITIATE:            'payroll.fnf.initiate',
  FNF_APPROVE:             'payroll.fnf.approve',
} as const;
