export const ORGANIZATION_PERMISSIONS = {
  COMPANY_VIEW: 'organization.company.view',
  COMPANY_CREATE: 'organization.company.create',
  COMPANY_EDIT: 'organization.company.edit',
  COMPANY_DELETE: 'organization.company.delete',
  DEPARTMENT_VIEW: 'organization.department.view',
  DEPARTMENT_CREATE: 'organization.department.create',
  DEPARTMENT_EDIT: 'organization.department.edit',
  DEPARTMENT_DELETE: 'organization.department.delete',
  DESIGNATION_VIEW: 'organization.designation.view',
  DESIGNATION_CREATE: 'organization.designation.create',
  DESIGNATION_EDIT: 'organization.designation.edit',
  DESIGNATION_DELETE: 'organization.designation.delete',
  GRADE_VIEW: 'organization.grade.view',
  GRADE_CREATE: 'organization.grade.create',
  GRADE_EDIT: 'organization.grade.edit',
  GRADE_DELETE: 'organization.grade.delete',
  LOCATION_VIEW: 'organization.location.view',
  LOCATION_CREATE: 'organization.location.create',
  LOCATION_EDIT: 'organization.location.edit',
  LOCATION_DELETE: 'organization.location.delete',
} as const;
