export const RBAC_PERMISSIONS = {
  ROLE_VIEW: 'rbac.role.view',
  ROLE_CREATE: 'rbac.role.create',
  ROLE_EDIT: 'rbac.role.edit',
  ROLE_DELETE: 'rbac.role.delete',
  PERMISSION_ASSIGN: 'rbac.permission.assign',
  USER_ASSIGN_ROLE: 'rbac.user.assign_role',
  DELEGATION_CREATE: 'rbac.delegation.create',
} as const;

export const ALL_SYSTEM_PERMISSIONS: Array<{
  code: string;
  module: string;
  action: string;
  description: string;
}> = [
  // Employee
  { code: 'employee.profile.view', module: 'employee', action: 'view', description: 'View employee profiles' },
  { code: 'employee.profile.edit', module: 'employee', action: 'edit', description: 'Edit employee profiles' },
  { code: 'employee.profile.create', module: 'employee', action: 'create', description: 'Create employees' },
  { code: 'employee.profile.delete', module: 'employee', action: 'delete', description: 'Delete employees' },
  { code: 'employee.salary.view', module: 'employee', action: 'view', description: 'View salary info' },
  { code: 'employee.bank_details.view', module: 'employee', action: 'view', description: 'View bank details' },
  { code: 'employee.bank_details.edit', module: 'employee', action: 'edit', description: 'Edit bank details' },
  { code: 'employee.statutory_details.view', module: 'employee', action: 'view', description: 'View statutory details' },
  { code: 'employee.documents.view', module: 'employee', action: 'view', description: 'View documents' },
  { code: 'employee.documents.upload', module: 'employee', action: 'upload', description: 'Upload documents' },
  { code: 'employee.documents.delete', module: 'employee', action: 'delete', description: 'Delete documents' },
  { code: 'employee.directory.view', module: 'employee', action: 'view', description: 'View employee directory' },
  { code: 'employee.personal_sensitive.view', module: 'employee', action: 'view', description: 'View sensitive personal info' },
  { code: 'employee.timeline.view', module: 'employee', action: 'view', description: 'View employee timeline' },
  { code: 'employee.ess.manage', module: 'employee', action: 'manage', description: 'Manage ESS access' },
  { code: 'employee.bulk_import', module: 'employee', action: 'import', description: 'Bulk import employees' },
  // Leave
  { code: 'leave.application.view', module: 'leave', action: 'view', description: 'View leave applications' },
  { code: 'leave.application.create', module: 'leave', action: 'create', description: 'Apply for leave' },
  { code: 'leave.application.edit', module: 'leave', action: 'edit', description: 'Edit leave applications' },
  { code: 'leave.application.cancel', module: 'leave', action: 'cancel', description: 'Cancel leave' },
  { code: 'leave.application.approve', module: 'leave', action: 'approve', description: 'Approve leave' },
  { code: 'leave.application.reject', module: 'leave', action: 'reject', description: 'Reject leave' },
  { code: 'leave.application.revoke', module: 'leave', action: 'revoke', description: 'Revoke leave' },
  { code: 'leave.balance.view', module: 'leave', action: 'view', description: 'View leave balances' },
  { code: 'leave.balance.adjust', module: 'leave', action: 'edit', description: 'Adjust leave balances' },
  { code: 'leave.policy.configure', module: 'leave', action: 'configure', description: 'Configure leave policies' },
  // Attendance
  { code: 'attendance.log.view', module: 'attendance', action: 'view', description: 'View attendance logs' },
  { code: 'attendance.log.override', module: 'attendance', action: 'override', description: 'Override attendance' },
  { code: 'attendance.regularization.approve', module: 'attendance', action: 'approve', description: 'Approve regularization' },
  { code: 'attendance.exception.view', module: 'attendance', action: 'view', description: 'View attendance exceptions' },
  { code: 'attendance.exception.approve', module: 'attendance', action: 'approve', description: 'Approve attendance exceptions' },
  { code: 'attendance.finalize', module: 'attendance', action: 'finalize', description: 'Finalize attendance' },
  { code: 'attendance.lock', module: 'attendance', action: 'lock', description: 'Lock attendance records' },
  { code: 'attendance.bulk_import', module: 'attendance', action: 'import', description: 'Bulk import attendance' },
  { code: 'attendance.shift.view', module: 'attendance', action: 'view', description: 'View shifts' },
  { code: 'attendance.shift.configure', module: 'attendance', action: 'configure', description: 'Configure shifts' },
  // Payroll
  { code: 'payroll.component.view',         module: 'payroll', action: 'view',     description: 'View salary components' },
  { code: 'payroll.component.manage',       module: 'payroll', action: 'manage',   description: 'Create and edit salary components' },
  { code: 'payroll.structure.view',         module: 'payroll', action: 'view',     description: 'View salary structures' },
  { code: 'payroll.structure.manage',       module: 'payroll', action: 'manage',   description: 'Create and edit salary structures' },
  { code: 'payroll.employee_salary.view',   module: 'payroll', action: 'view',     description: 'View employee salary details' },
  { code: 'payroll.employee_salary.assign', module: 'payroll', action: 'assign',   description: 'Assign salary structure to employee' },
  { code: 'payroll.employee_salary.revise', module: 'payroll', action: 'revise',   description: 'Revise employee salary' },
  { code: 'payroll.cycle.manage',           module: 'payroll', action: 'manage',   description: 'Manage pay cycles' },
  { code: 'payroll.inputs.manage',          module: 'payroll', action: 'manage',   description: 'Enter payroll inputs (LOP/bonus)' },
  { code: 'payroll.run.view',               module: 'payroll', action: 'view',     description: 'View payroll runs' },
  { code: 'payroll.run.create',             module: 'payroll', action: 'create',   description: 'Create payroll runs' },
  { code: 'payroll.run.finalize',           module: 'payroll', action: 'finalize', description: 'Finalize payroll' },
  { code: 'payroll.run.approve',            module: 'payroll', action: 'approve',  description: 'Approve payroll' },
  { code: 'payroll.run.rollback',           module: 'payroll', action: 'rollback', description: 'Rollback a payroll run' },
  { code: 'payroll.payslip.view',           module: 'payroll', action: 'view',     description: 'View payslips' },
  { code: 'payroll.payslip.publish',        module: 'payroll', action: 'publish',  description: 'Publish payslips' },
  { code: 'payroll.statutory.manage',       module: 'payroll', action: 'manage',   description: 'Configure statutory settings (PF/ESI/PT/TDS)' },
  { code: 'reports.sensitive.export', module: 'reports', action: 'export', description: 'Export sensitive reports' },
  // RBAC
  { code: 'rbac.role.view', module: 'rbac', action: 'view', description: 'View roles' },
  { code: 'rbac.role.create', module: 'rbac', action: 'create', description: 'Create roles' },
  { code: 'rbac.role.edit', module: 'rbac', action: 'edit', description: 'Edit roles' },
  { code: 'rbac.role.delete', module: 'rbac', action: 'delete', description: 'Delete roles' },
  { code: 'rbac.permission.assign', module: 'rbac', action: 'assign', description: 'Assign permissions' },
  { code: 'rbac.user.assign_role', module: 'rbac', action: 'assign', description: 'Assign roles to users' },
  { code: 'rbac.delegation.create', module: 'rbac', action: 'create', description: 'Create delegations' },
  // Organization
  { code: 'organization.company.view', module: 'organization', action: 'view', description: 'View companies' },
  { code: 'organization.company.create', module: 'organization', action: 'create', description: 'Create companies' },
  { code: 'organization.company.edit', module: 'organization', action: 'edit', description: 'Edit companies' },
  { code: 'organization.company.delete', module: 'organization', action: 'delete', description: 'Delete companies' },
  { code: 'organization.department.view', module: 'organization', action: 'view', description: 'View departments' },
  { code: 'organization.department.create', module: 'organization', action: 'create', description: 'Create departments' },
  { code: 'organization.department.edit', module: 'organization', action: 'edit', description: 'Edit departments' },
  { code: 'organization.department.delete', module: 'organization', action: 'delete', description: 'Delete departments' },
  { code: 'organization.designation.view', module: 'organization', action: 'view', description: 'View designations' },
  { code: 'organization.designation.create', module: 'organization', action: 'create', description: 'Create designations' },
  { code: 'organization.designation.edit', module: 'organization', action: 'edit', description: 'Edit designations' },
  { code: 'organization.designation.delete', module: 'organization', action: 'delete', description: 'Delete designations' },
  { code: 'organization.grade.view', module: 'organization', action: 'view', description: 'View grades' },
  { code: 'organization.grade.create', module: 'organization', action: 'create', description: 'Create grades' },
  { code: 'organization.grade.edit', module: 'organization', action: 'edit', description: 'Edit grades' },
  { code: 'organization.grade.delete', module: 'organization', action: 'delete', description: 'Delete grades' },
  { code: 'organization.location.view', module: 'organization', action: 'view', description: 'View locations' },
  { code: 'organization.location.create', module: 'organization', action: 'create', description: 'Create locations' },
  { code: 'organization.location.edit', module: 'organization', action: 'edit', description: 'Edit locations' },
  { code: 'organization.location.delete', module: 'organization', action: 'delete', description: 'Delete locations' },
  { code: 'organization.authority_signature.view', module: 'organization', action: 'view', description: 'View authority signatures' },
  { code: 'organization.authority_signature.create', module: 'organization', action: 'create', description: 'Create authority signatures' },
  { code: 'organization.authority_signature.edit', module: 'organization', action: 'edit', description: 'Edit authority signatures' },
  { code: 'organization.authority_signature.delete', module: 'organization', action: 'delete', description: 'Delete authority signatures' },
  // Tenant
  { code: 'tenant.settings.view', module: 'tenant', action: 'view', description: 'View tenant settings' },
  { code: 'tenant.settings.edit', module: 'tenant', action: 'edit', description: 'Edit tenant settings' },
  { code: 'tenant.modules.configure', module: 'tenant', action: 'configure', description: 'Configure modules' },
  { code: 'tenant.billing.view', module: 'tenant', action: 'view', description: 'View billing' },
  { code: 'tenant.billing.manage', module: 'tenant', action: 'manage', description: 'Manage billing' },
  { code: 'tenant.company.create', module: 'tenant', action: 'create', description: 'Create companies' },
  { code: 'tenant.company.edit', module: 'tenant', action: 'edit', description: 'Edit companies' },
  { code: 'tenant.audit_log.view', module: 'tenant', action: 'view', description: 'View audit logs' },
  { code: 'tenant.audit_log.export', module: 'tenant', action: 'export', description: 'Export audit logs' },
  { code: 'tenant.user.create_admin', module: 'tenant', action: 'create', description: 'Create admin users' },
  { code: 'tenant.data.export', module: 'tenant', action: 'export', description: 'Export tenant data' },
  // AI
  { code: 'ai.chatbot.use', module: 'ai', action: 'use', description: 'Use AI chatbot' },
  { code: 'ai.settings.configure', module: 'ai', action: 'configure', description: 'Configure AI settings' },
  { code: 'ai.usage.view', module: 'ai', action: 'view', description: 'View AI usage' },
  // Notifications
  { code: 'notification.view', module: 'notification', action: 'view', description: 'View notifications' },
  { code: 'notification.template.view', module: 'notification', action: 'view', description: 'View notification templates' },
  { code: 'notification.template.create', module: 'notification', action: 'create', description: 'Create notification templates' },
  { code: 'notification.template.edit', module: 'notification', action: 'edit', description: 'Edit notification templates' },
  // Workflow
  { code: 'workflow.view', module: 'workflow', action: 'view', description: 'View workflow definitions' },
  { code: 'workflow.configure', module: 'workflow', action: 'configure', description: 'Configure workflows' },
  { code: 'workflow.instance.view', module: 'workflow', action: 'view', description: 'View workflow instances' },
  { code: 'workflow.instance.approve', module: 'workflow', action: 'approve', description: 'Approve/reject workflow steps' },
  // Rule engine
  { code: 'rule.view', module: 'rule-engine', action: 'view', description: 'View rule sets' },
  { code: 'rule.configure', module: 'rule-engine', action: 'configure', description: 'Configure rules' },
  // Dynamic forms
  { code: 'form.view', module: 'dynamic-forms', action: 'view', description: 'View forms' },
  { code: 'form.configure', module: 'dynamic-forms', action: 'configure', description: 'Configure forms' },
  // Loans
  { code: 'payroll.loan.view',    module: 'payroll', action: 'view',    description: 'View loan requests' },
  { code: 'payroll.loan.create',  module: 'payroll', action: 'create',  description: 'Request a loan' },
  { code: 'payroll.loan.approve', module: 'payroll', action: 'approve', description: 'Approve/reject loan requests' },
  // FnF
  { code: 'payroll.fnf.view',     module: 'payroll', action: 'view',     description: 'View FnF settlements' },
  { code: 'payroll.fnf.initiate', module: 'payroll', action: 'initiate', description: 'Initiate FnF for an employee' },
  { code: 'payroll.fnf.approve',  module: 'payroll', action: 'approve',  description: 'Approve FnF settlement' },
  // Overtime
  { code: 'attendance.overtime.view',    module: 'attendance', action: 'view',    description: 'View overtime records' },
  { code: 'attendance.overtime.submit',  module: 'attendance', action: 'submit',  description: 'Submit overtime request' },
  { code: 'attendance.overtime.approve', module: 'attendance', action: 'approve', description: 'Approve overtime requests' },
  // Expense & Claims
  { code: 'expense.claim.view', module: 'expense', action: 'view', description: 'View expense claims' },
  { code: 'expense.claim.create', module: 'expense', action: 'create', description: 'Create expense claims' },
  { code: 'expense.claim.submit', module: 'expense', action: 'submit', description: 'Submit expense claims for approval' },
  { code: 'expense.claim.approve', module: 'expense', action: 'approve', description: 'Approve expense claims' },
  { code: 'expense.claim.reject', module: 'expense', action: 'reject', description: 'Reject expense claims' },
  { code: 'expense.category.view', module: 'expense', action: 'view', description: 'View expense categories' },
  { code: 'expense.category.configure', module: 'expense', action: 'configure', description: 'Configure expense categories' },
  // Reports & Analytics
  { code: 'reports.standard.view',   module: 'reports', action: 'view',    description: 'View and generate standard reports' },
  { code: 'reports.standard.export', module: 'reports', action: 'export',  description: 'Export reports as CSV' },
  { code: 'reports.analytics.view',  module: 'reports', action: 'view',    description: 'View analytics dashboard' },
  // Integrations
  { code: 'integrations.api_client.manage', module: 'integrations', action: 'manage', description: 'Create and manage API clients' },
  { code: 'integrations.webhook.manage',    module: 'integrations', action: 'manage', description: 'Create and manage webhooks' },
];
